### ISSUE TITLE
Incomplete transcription

### ISSUE THREAD

**Issue by DevRGT** [vivek-nexus/transcriptonic#13]
Hello,

Thanky a lot for the Google Meet extension :-)

I had a meeting, starting at about 09:00 and endding at 09:42.
When I downloaded the "last transcription Meeting", I got very few transcriptions, only from 09:00 to 09:06.

With Teams Meeting, I'm using this extension: https://github.com/Zerg00s/Live-Captions-Saver and I don't have this issue.
Maybe you could find some ideas for this Teams Extension for your Google Meeti Extension.

**Comment by vivek-nexus** [comment]
Thanks for flagging this. Ideally, this should not have happened. Please help me with answers to these questions so that I can understand the source of the problem.

1. Is this one time issue or does it happen in every meeting / most meetings?
2. Is TranscripTonic in auto mode or manual mode when this issue happens?
3. You must have seen a auto downloaded transcript file for this meeting (irrespective of auto mode / manual mode) . Are things missing in that file as well, or missing only in the file you downloaded when you clicked `Download last transcript meeting`?
4. Did you turn off Google Meet transcript in the middle of the meeting, by pressing `C` key or by clicking on the captions icon?
5. Did TranscripTonic show any error notification during the meeting or at the end of the meeting?
6. Did you end the meeting by clicking on the red button on the screen or by closing the meeting tab directly?

**Comment by DevRGT** [comment]
Hello,

thank you for your reply.
1) Just one time. I had activated the transcription directly in Google Chrome settings. So I had a movable frame with the transcription (without a speakers information) and I think I closed it.
2) Auto mode
3) Was missing in every flle linked to this session
4) I think yes, regarding this movable frame, but no idea how I closed it, the other transcription were still runnin
5)  No
6) Sorry, I don't remember

**Comment by vivek-nexus** [comment]
Okay. Closing this as one time issue. TranscripTonic will handle turning on the captions everytime (for auto mode), so you can keep it off in settings.

**Comment by DevRGT** [comment]
Maybe I was not clear.
I had the transcription under the shared screen display.
Like
You: .....
Speaker 1: .....

But I had a second transcription window from Accessibility settings.
This one was just with text transcription without who is talking. 
It's this one I closed
