### ISSUE TITLE
No new Captions since 04/07/2024

### ISSUE THREAD

**Issue by DevRGT** [vivek-nexus/transcriptonic#20]
Hello,
Since few days it seems the extension is not working anymore.
The automatic download is set on, but after a meeting, there is no download and when I click on "Download last meeting transcript", I get the exact same file as my meeting on the 04/07/2024.
So it seems there is no more caption.

I have the last version 2.1.3

**Comment by vivek-nexus** [comment]
Thanks for raising this. I am not able to reproduce this issue on my end.

Reasons could be
1. Google Meet might be running A/B testing where the Meet page that loads for each user might be different.
2. Google Meet might have pushed an update to the web page. You have received the update and I am yet to receive it (unlikely since you say it is from 04/07).
3. Something might be preventing TranscripTonic from running or operating (some other extension or change in Chrome settings).

Further information is needed to debug the issue. Please share what you see in console tab of browser devtools. If TranscripTonic is allowed to run properly, you should either see your transcripts being logged to the console or error messages from TranscripTonic logged to the console. If you don't see anything relevant, then it most likely point 3 above.

**Comment by vivek-nexus** [comment]
@DevRGT

**Comment by helbertparanhos** [comment]
@vivek-nexus I have the same problem
 Apparently on a Google account Chorme works normally, but when installing on a new account, it does not download the message transcription. I've already reviewed the settings and reset the permissions, but nothing resolved it.
 
 Any idea what browser setting might affect this?

**Comment by vivek-nexus** [comment]
@DevRGT refer #21. I hope this solves your issue as well.

**Comment by DevRGT** [comment]
Hello,
Thank you very much.
It seems working now.
I did just a short test.
I will let you know if I see issues.

Hands up :-)
