### ISSUE TITLE
No transcripts in new Meet UI

### ISSUE THREAD

**Issue by helbertparanhos** [vivek-nexus/transcriptonic#21]
@vivek-nexus I have the same problem as #20 
Apparently on a Google account Chorme works normally, but when installing on a new account, it does not download the message transcription. I've already reviewed the settings and reset the permissions, but nothing resolved it.

Any idea what browser setting might affect this? 

Version -> 2.1.3
![2024-08-04 01_46_29-Window](https://github.com/user-attachments/assets/819a9162-bde1-4f94-8da3-e1e7ff93e45a)

**Comment by vivek-nexus** [comment]
@helbertparanhos Thanks for flagging this and sharing additional information.

From your screenshot, it is clear that the extension is set up, installed and loading properly. No interference from browser or other extensions. The two logs indicate that the extension starts working on a meeting page.

Your screenshot further gives me a feeling that Google Meet is definitely loading a different version of the page for different users. Possibly A/B testing or a phased roll-out of UI upgrades, which is why I am not able to reproduce this issue on my end.

Since I cannot (yet) reproduce this on my end, can you help me with the following points? You can also send these by email to the support email of the extension, if you are not willing to share this publicly on a GitHub issue.
1. Do you see any UI differences between the meeting where the extension works properly and where it does not work? For example, I can the buttons for video and caption are rounded rectangles. Earlier they used to be all full circles.
2. In the meeting where TranscripTonic does not work, do you see a notification `TranscripTonic is running, Do not turn off captions`, when meeting starts?
3. If you know how to use devtools to inspect HTML elements, can you share the 2nd child HTML of `END CALL` button and `CAPTIONS` button? I suspect this is where the problem is most likely happening. New UI has different classes and the extension depends on classes of older UI. This is how it looks in the old UI: 
- END CALL: `<i class="google-material-icons VfPpkd-kBDsod" aria-hidden="true">call_end</i>`
- CAPTIONS: `<span aria-hidden="true" class="material-icons-extended VfPpkd-Bz112c-kBDsod-OWXEXe-IT5dJd VfPpkd-Bz112c-kBDsod">closed_caption</span>`

**Comment by helbertparanhos** [comment]
Thank you for the quick response!
Yes, here is the information:

1- Yes, the two are completely different in terms of UI, I'll send the images below.

This is the new UI where the extension is not working:
![2024-08-04 10_32_43-Window](https://github.com/user-attachments/assets/43b53115-697d-4fa7-a5ad-c00430a057ff)


This is the old UI where the extension works normally:
![2024-08-04 10_28_59-Window](https://github.com/user-attachments/assets/887f44f0-0613-4ed7-b61f-4d8a93c058f3)

2- No, in the new UI it does not activate the extension automatically, so it does not show the notification either ( TranscripTonic is running, Do not turn off captions)

3- Of course, here is the information:

This is the new UI where the extension is not working:

END CALL:
![2024-08-04 10_35_31-](https://github.com/user-attachments/assets/fa03a926-09c3-4061-9e8a-ea98b3b0d372)


CAPTIONS:
![2024-08-04 10_34_46-Window](https://github.com/user-attachments/assets/005af00b-7168-4830-95cf-52a9adbac7f5)

Please let me know if you want me to paste the code here instead of a screenshot. And I am at your disposal if you need to access my computer via Anydesk, I believe I can help too

**Comment by vivek-nexus** [comment]
@helbertparanhos information you've provided in 1 and 2 is helpful to narrow down the issue in 3, thanks!

Google Meet loading different UI for different users is the source of the issue. I do have decent error capturing and logging in place built into the extension, but this change is not something error logging cannot capture.

For 3, yes it would be helpful if you can share full HTML (with all nested child elements fully expanded), for both the buttons. I don't want to access your machine because I have to [test](https://github.com/vivek-nexus/transcriptonic/wiki/Test-cases) extensively as well. So I will have to wait until I get this update on my end, but I can keep the changes ready by using the code you share.

**Comment by helbertparanhos** [comment]
CAPTIONS:

`<div class="juFBl" jslog="211197; track:JIbuQc;" jscontroller="iBwifb" jsaction="JIbuQc:QODBq;rcuQ6b:KpAaTb;Z1rKi:KpAaTb" tooltip-id="ucc-18"><span data-is-tooltip-wrapper="true"><button class="VYBDae-Bz112c-LgbsSe VYBDae-Bz112c-LgbsSe-OWXEXe-ornU0b VYBDae-Bz112c-LgbsSe-OWXEXe-SfQLQb-suEOdc eMJrtf Ms2Zcd c1y6pf " jscontroller="WD3M3d" jsaction="click:h5M12e; clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox;focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;" data-idom-class="eMJrtf Ms2Zcd c1y6pf " jsname="r8qRAd" aria-label="Turn on captions" aria-pressed="false" data-sync-idom-state="true" data-tooltip-enabled="true" data-tooltip-id="ucc-18" data-tooltip-x-position="3" data-tooltip-y-position="2" data-tooltip-classes="PJU52b " role="button"><span class="OiePBf-zPjgPe VYBDae-Bz112c-UHGRz"></span><span class="RBHQF-ksKsZd" data-unbounded="false" jscontroller="LBaJxb" jsname="m9ZlFb"></span><span jsname="Hjh9Ae" aria-hidden="true" class="material-icons-extended VYBDae-Bz112c-kBDsod-Rtc0Jf VYBDae-Bz112c-kBDsod-Rtc0Jf-OWXEXe-IT5dJd"><i aria-hidden="true" class="google-symbols ebW6mc">closed_caption</i></span><span jsname="S5tZuc" aria-hidden="true" class="material-icons-extended VYBDae-Bz112c-kBDsod-Rtc0Jf"><i aria-hidden="true" class="google-symbols ebW6mc">closed_caption_off</i></span><div class="VYBDae-Bz112c-RLmnJb"></div></button><div class="ne2Ple-oshW8e-V67aGc" role="tooltip" aria-hidden="true" id="ucc-18">Turn on captions (c)</div></span></div>`

END CALL:
`<div jslog="211198; track:JIbuQc;" jscontroller="m1IMT" jsaction="JIbuQc:wB8Z8d" class="NHaLPe"><span data-is-tooltip-wrapper="true"><button class="VYBDae-Bz112c-LgbsSe VYBDae-Bz112c-LgbsSe-OWXEXe-SfQLQb-suEOdc hk9qKe  Iootmd vLQezd " jscontroller="PIVayb" jsaction="click:h5M12e; clickmod:h5M12e;pointerdown:FEiYhc;pointerup:mF5Elf;pointerenter:EX0mI;pointerleave:vpvbp;pointercancel:xyn4sd;contextmenu:xexox;focus:h06R8; blur:zjh6rb;mlnRJb:fLiPzd;" data-idom-class="hk9qKe  Iootmd vLQezd " jsname="CQylAd" aria-label="Leave call" data-tooltip-enabled="true" data-tooltip-id="tt-c219" data-tooltip-x-position="3" data-tooltip-y-position="2" data-tooltip-classes="PJU52b " role="button"><span class="OiePBf-zPjgPe VYBDae-Bz112c-UHGRz"></span><span class="RBHQF-ksKsZd RBHQF-ksKsZd-OWXEXe-ZmdkE" data-unbounded="false" jscontroller="LBaJxb" jsname="m9ZlFb"></span><span jsname="S5tZuc" aria-hidden="true" class="VYBDae-Bz112c-kBDsod-Rtc0Jf"><i aria-hidden="true" class="google-symbols ebW6mc">call_end</i></span><div class="VYBDae-Bz112c-RLmnJb"></div></button><div class="ne2Ple-oshW8e-V67aGc" role="tooltip" aria-hidden="true" id="tt-c219">Leave call</div></span></div>`

If you want, I can test the change here, just tell me how I should do it @vivek-nexus

**Comment by vivek-nexus** [comment]
Thanks @helbertparanhos. Let me rework the code to work for both UIs. I'll get back here with an update. Might take a couple of days, in the middle of other things I have.

**Comment by helbertparanhos** [comment]
Perfect, thanks for the help. If you need any more information, I am at your disposal. @vivek-nexus

**Comment by vivek-nexus** [comment]
@helbertparanhos I've pushed the code to [to this branch](https://github.com/vivek-nexus/transcriptonic/tree/v2.2.0). You can download code from that branch, sideload the "extension" folder in Chrome and try it. This should work for both UIs, old and new. I'll push this to Chrome store soon, after some more testing on my end.

Fortunately, I too got the new UI on my end. So along with your code, this helped me rework the code.

**Comment by vivek-nexus** [comment]
No worries @helbertparanhos. Thanks for the time you took to raise the issue and provide information to properly debug (most people tend to uninstall and move on).

You may remove the side loaded extension. The one you installed from Chrome store will auto update when the update is live on the Chrome store.
